[package]
name = "vec-utils"
version = "0.1.2"
authors = ["Ozaren <krishna.sd.2012@gmail.com>"]
edition = "2018"

readme = "README.md"
license = "MIT"
description = "vector utilities"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
